import ObjectBox
import Foundation
import Combine

@MainActor
public final class LocalStore: ObservableObject {
    @Published public var cachedFeed: [FeedViewPost] = []
    @Published public var savedPostUris: Set<String> = []
    @Published public var readPostUris: Set<String> = []
    @Published public var localAbuseScores: [String: Double] = [:]
    
    private var store: Store?
    private var postBox: Box<CachedPostEntity>?
    
    public init() {
        do {
            let paths = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)
            let directory = paths[0].appendingPathComponent("SwiftPaperATProto", isDirectory: true)
            try FileManager.default.createDirectory(at: directory, withIntermediateDirectories: true)
            
            // Initialize Store (setup generated by ObjectBox build plugin)
            self.store = try Store(directoryPath: directory.path)
            if let store = store {
                self.postBox = store.box(for: CachedPostEntity.self)
            }
        } catch {
            print("Failed to initialize ObjectBox store: \(error.localizedDescription)")
        }
        
        loadFromDatabase()
    }
    
    private func loadFromDatabase() {
        guard let box = postBox else { return }
        do {
            let entities = try box.all()
            self.cachedFeed = entities.map { $0.toFeedViewPost() }
            self.savedPostUris = Set(entities.filter { $0.isSaved }.map { $0.uri })
            self.readPostUris = Set(entities.filter { $0.isRead }.map { $0.uri })
            
            var scores: [String: Double] = [:]
            for entity in entities {
                scores[entity.uri] = entity.localAbuseScore
            }
            self.localAbuseScores = scores
        } catch {
            print("Failed to read from ObjectBox database: \(error.localizedDescription)")
        }
    }
    
    // MARK: - Cache Management
    public func cacheFeed(_ feed: [FeedViewPost]) {
        guard let box = postBox else { return }
        
        do {
            let entities = try box.all()
            
            // Perform writes inside database transaction
            try store?.runInTransaction {
                for item in feed {
                    let uri = item.post.uri
                    let existing = entities.first(where: { $0.uri == uri })
                    
                    let isSaved = existing?.isSaved ?? savedPostUris.contains(uri)
                    let isRead = existing?.isRead ?? readPostUris.contains(uri)
                    
                    var score = localAbuseScores[uri] ?? existing?.localAbuseScore
                    if score == nil {
                        let text = item.post.record.text
                        if text.contains("!!!") || text.uppercased() == text {
                            score = Double.random(in: 0.4...0.7)
                        } else {
                            score = Double.random(in: 0.01...0.15)
                        }
                    }
                    
                    let entity = CachedPostEntity(from: item, isSaved: isSaved, isRead: isRead, abuseScore: score ?? 0.0)
                    if let old = existing {
                        entity.id = old.id
                    }
                    try box.put(entity)
                }
            }
        } catch {
            print("Failed to update cache in ObjectBox: \(error.localizedDescription)")
        }
        
        loadFromDatabase()
    }
    
    public func clearCache() {
        guard let box = postBox else { return }
        do {
            try box.removeAll()
        } catch {
            print("Failed to clear ObjectBox database: \(error.localizedDescription)")
        }
        loadFromDatabase()
    }
    
    // MARK: - Post Interaction State
    public func toggleSavePost(uri: String) {
        guard let box = postBox else { return }
        do {
            let entities = try box.all()
            if let entity = entities.first(where: { $0.uri == uri }) {
                entity.isSaved.toggle()
                try box.put(entity)
            }
        } catch {
            print("Failed to toggle save state in ObjectBox: \(error.localizedDescription)")
        }
        loadFromDatabase()
    }
    
    public func markAsRead(uri: String) {
        guard let box = postBox else { return }
        do {
            let entities = try box.all()
            if let entity = entities.first(where: { $0.uri == uri }) {
                entity.isRead = true
                try box.put(entity)
            }
        } catch {
            print("Failed to mark post as read in ObjectBox: \(error.localizedDescription)")
        }
        loadFromDatabase()
    }
    
    public func isSaved(uri: String) -> Bool {
        savedPostUris.contains(uri)
    }
    
    public func isRead(uri: String) -> Bool {
        readPostUris.contains(uri)
    }
}
